FROM ubuntu:20.04

RUN apt update -y && \
    apt install -y git python3

ARG CACHE_DISTURB
RUN git clone https://github.com/nohhyejin1/study_DockerSwarm
WORKDIR /study_DockerSwarm

CMD ["python3", "hello.py"]